# PDDLStream problem
pddlstream:
  algorithm: adaptive
  unit: True
  deterministic: True
  problem: fmb_momo_problem
  cfree: True
  teleport: False

# cuRobo
curobo:
  robot_cfg: # load from curobo content/config/robot
    yaml: xarm7.yml
  world_cfg: # load from curobo content/config/world
    table:
      type: cuboid
      yaml: collision_table.yml
  robot_world_cfg:
    robot_file: xarm7.yml
    activation_distance: 0.0
    nvblox: friction_correlation_distance
  world_collision_cfg:
    cache: null
    checker_type: "PRIMITIVE" # ["PRIMITIVE", "BLOX", "MESH"]
    max_distance: 0.1
  motion_generation_plan_cfg:
    enable_graph: True
    enable_graph_attempt: 4
    max_attempts: 2
    enable_finetune_trajopt: True
    parallel_finetune: True
  ik_solver_cfg:
    position_threshold: 0.05
    rotation_threshold: 0.005
    num_seeds: 20
    self_collision_check: True
    self_collision_opt: True
    use_cuda_graph: True
    n_obstacle_cuboids: 1
    n_obstacle_mesh: 4
  motion_gen_cfg:
    num_trajopt_seeds: 10
    num_grarph_seeds: 10
    interpolation_dt: 0.01
    n_obstacle_cuboids: 1
    n_obstacle_mesh: 4
    num_graph_seeds: 2
    optimize_dt: 0.01
    trajopt_dt: 0.01
    trajopt_tsteps: 4
    trim_steps: 3
    use_cuda_graph: False
    enable_graph: False
    warmup_js_trajopt: False
    parallel_finetune: False
  mpc_cfg:
    use_cuda_graph: False
    use_cuda_graph_metrics: False
    use_cuda_graph_full_step: False
    self_collision_check: True
    n_obstacle_cuboids: 1
    n_obstacle_mesh: 4
    use_mppi: False
    use_lbfgs: False
    store_rollouts: False
    step_dt: 0.01

# Simulation environment
sim:
  dt: 0.00833333333 # 1/120 s
  use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
  gravity: [0.0, 0.0, -9.81]
  disable_gravity: False
  add_ground_plane: True
  add_distant_light: True
  use_flatcache: True
  enable_scene_query_support: True
  disable_contact_processing: False
  enable_cameras: False # set to True if you use camera sensors in the environment

  default_physics_material:
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0

  physx:
    worker_thread_count: ${....num_threads}
    solver_type: ${....solver_type}
    use_gpu: ${eq:${....sim_device},"gpu"} # set to False to run on CPU
    solver_position_iteration_count: 32
    solver_velocity_iteration_count: 16
    contact_offset: 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    friction_offset_threshold: 0.01
    friction_correlation_distance: 0.025
    enable_sleeping: True
    enable_stabilization: True
    max_depenetration_velocity: 1000.0

    # GPU buffers
    gpu_max_rigid_contact_count: 16777216
    gpu_max_rigid_patch_count: 33554432
    gpu_found_lost_pairs_capacity: 17060160
    gpu_found_lost_aggregate_pairs_capacity: 17060160
    gpu_total_aggregate_pairs_capacity: 16777216
    gpu_max_soft_body_contacts: 16777216
    gpu_max_particle_contacts: 16777216
    gpu_heap_capacity: 33554432
    gpu_temp_buffer_capacity: 16777216
    gpu_max_num_partitions: 8
    gpu_collision_stack_size: 33554432

  # sim asset configs here
  floor:
    size: 100.0
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0

  table:
    translation: [0.3, 0.0, 0.0]
    orientation: [1.0, 0.0, 0.0, 0.0]
    color: [0.0, 0.0, 0.0]
    width: 1.0
    depth: 1.0
    height: 0.1
    size: 1.0

  robot:
    name: xarm7
    translation: [0.0, 0.0, 0.1]
    orientation: [1.0, 0.0, 0.0, 0.0]

  base_block:
    name: base_block
    task: momo
    translation: [0.3, -0.2, 0.1]
    orientation: [1.0, 0.0, 0.0, 0.0]

  block1:
    name: block1
    task: momo
    translation: [0.3, 0.0, 0.1]
    orientation: [1.0, 0.0, 0.0, 0.0]

  block2:
    name: block2
    task: momo
    translation: [0.4, 0.1, 0.1]
    orientation: [1.0, 0.0, 0.0, 0.0]

  block3:
    name: block3
    task: momo
    translation: [0.4, 0.0, 0.1]
    orientation: [1.0, 0.0, 0.0, 0.0]

  block4:
    name: block4
    task: momo
    translation: [0.3, 0.1, 0.1]
    orientation: [1.0, 0.0, 0.0, 0.0]

  surface1:
    name: surface1
    translation: [0.0, 0.0, 0.0]
    orientation: [1.0, 0.0, 0.0, 0.0]

  surface2:
    name: surface2
    translation: [0.0, 0.0, 0.11]
    orientation: [1.0, 0.0, 0.0, 0.0]

  surface3:
    name: surface3
    translation: [0.0, 0.0, 0.11]
    orientation: [1.0, 0.0, 0.0, 0.0]

  surface4:
    name: surface4
    translation: [0.0, 0.0, 0.11]
    orientation: [1.0, 0.0, 0.0, 0.0]

  hole1:
    name: hole1
    translation: [0.0, 0.0, 0.0]
    orientation: [1.0, 0.0, 0.0, 0.0]

  hole2:
    name: hole2
    translation: [0.0, 0.0, 0.0]
    orientation: [1.0, 0.0, 0.0, 0.0]

  hole3:
    name: hole3
    translation: [0.0, 0.0, 0.0]
    orientation: [1.0, 0.0, 0.0, 0.0]

  hole4:
    name: hole4
    translation: [0.0, 0.0, 0.0]
    orientation: [1.0, 0.0, 0.0, 0.0]

  parts:
    mass: 0.01
    density: 5000
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0

  gripper:
    mass: 0.01
    density: 100
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0

