# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: 1024

# seed - set to -1 to choose random seed
seed: -1
# set to True for deterministic performance
torch_deterministic: False

# (Optional) Use the isaac sim configuration from file
sim_app_cfg_path: "" # "/isaac_app_configs/omni.isaac.sim.python.kit"
# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: 1500

## Device config
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu' # 'cpu' or 'gpu'
# whether to use cpu or gpu physx
sim_device: 'gpu' # 'cpu' or 'gpu'
# used for gpu simulation only - device id for running sim and task if pipeline=gpu
device_id: 0
# device to run RL
rl_device: 'cuda:0' #'cpu' or 'cuda:0'
# multi-GPU training
multi_gpu: False

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs

# RL Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# used to set checkpoint path
checkpoint: ''

# enable/disable headless mode and rendering (in pygame window)
headless: False
# enables native livestream
enable_livestream: False
# timeout for MT script
mt_timeout: 30

# Wandb settings (optional)
wandb_activate: True
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'tamp-hsr'

# set default task and default training config based on task
defaults:
  - task: xArmFMBPick
  - train: ${task}PPO
  - hydra/job_logging: disabled

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .